export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS";
export const GET_LOGO_FAILURE = "GET_LOGO_FAILURE";
export const GET_PORTFOLIO_SUCCESS = "GET_PORTFOLIO_SUCCESS"
export const GET_PORTFOLIO_FAILURE = "GET_PORTFOLIO_FAILURE"
